version: 0.2

phases:
  build:
    commands:
      - echo Enter on buils phase
      - mvn clean package
  post_build:
    commands:
      - echo Build finalized succesfully
artifacts:
  files:
    - target/final_project_itexperts.jar
  discard-paths: yes